on:
  push:
    tags:
       - '*.[sc]'

name: Neuroconductor-check

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Get tag name
        id: get_tag_name
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag_name.outputs.VERSION }}
          release_name: Neuroc Release ${{ steps.get_tag_name.outputs.VERSION }}
          draft: false
          prerelease: false

  neuroconductor_check:
    needs: create_release
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macOS-latest,   r: 'devel',   r_ver: '4.1', latex: "true"}
          - {os: windows-latest, r: 'devel',   r_ver: '4.1'}
          - {os: ubuntu-16.04,   r: 'devel',   r_ver: '4.1', latex: "true", rspm: "https://packagemanager.rstudio.com/cran/__linux__/xenial/latest"}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      TIC_DEPLOY_KEY: ${{ secrets.TIC_DEPLOY_KEY }}
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-tinytex@master
        if: matrix.config.latex == 'true'

      - name: Install additional latex modules
        if: matrix.config.latex == 'true'
        run: |
          tlmgr update --self
          tlmgr install filecontents upquote courier courier-scaled biber biblatex collection-luatex
          tlmgr update --all

      - uses: r-lib/actions/setup-pandoc@master

      - name: Get repo name
        uses: adigherman/actions/get-repo-name@v1
        id: get-name
        with:
          github_slug: ${{ github.repository }}

      - name: Get the repo version (windows)
        if: runner.os == 'Windows'
        id: get_pkg_version_win
        run: |
          echo ::set-output name=PKG_VER::$(Rscript.exe -e "cat(read.dcf('DESCRIPTION')[, 'Version'])")
        shell: bash

      - name: Get the repo version (macOS/ubuntu)
        if: runner.os != 'Windows'
        id: get_pkg_version_nonwin
        run: |
          echo ::set-output name=PKG_VER::$(Rscript -e 'cat(read.dcf("DESCRIPTION")[, "Version"])')
        shell: bash

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        env:
          RHUB_PLATFORM: linux-x86_64-ubuntu-gcc
        run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
          remotes::install_github("ropensci/tic")
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      - name: Before Check
        run: Rscript -e "tic::before_install()"

      - name: "Check"
        run: |
          Rscript -e 'tic::script()'
          ls -l check
        shell: bash

      - name: Show testthat output
        if: always()
        run: find check -name 'testthat.Rout*' -exec cat '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@master
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Before Deploy
        run: Rscript -e "tic::before_deploy()"

      - name: Upload Release Asset (linux-x64)
        if: runner.os == 'Linux'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: check/${{ steps.get-name.outputs.repo_name }}_${{ steps.get_pkg_version_nonwin.outputs.PKG_VER }}_R_x86_64-pc-linux-gnu.tar.gz
          asset_name: ${{ steps.get-name.outputs.repo_name }}_${{ steps.get_pkg_version_nonwin.outputs.PKG_VER }}_R_x86_64-pc-linux-gnu_R${{ matrix.config.r_ver }}.tar.gz
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: check/${{ steps.get-name.outputs.repo_name }}_${{ steps.get_pkg_version_nonwin.outputs.PKG_VER }}.tgz
          asset_name: ${{ steps.get-name.outputs.repo_name }}_${{ steps.get_pkg_version_nonwin.outputs.PKG_VER }}_R${{ matrix.config.r_ver }}.tgz
          asset_content_type: application/octet-stream

      - name: Upload Release Asset (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: check/${{ steps.get-name.outputs.repo_name }}_${{ steps.get_pkg_version_win.outputs.PKG_VER }}.zip
          asset_name: ${{ steps.get-name.outputs.repo_name }}_${{ steps.get_pkg_version_win.outputs.PKG_VER }}_R${{ matrix.config.r_ver }}.zip
          asset_content_type: application/octet-stream

      - name: Deploy
        run: Rscript -e "tic::deploy()"

      - name: After Deploy
        run: Rscript -e "tic::after_deploy()"
